//! Lexer entry point — [`Lexer`] struct and public tokenization API.
//!
//! This module implements the character-stream primitives and dispatches to the
//! `parser` sub-module, which adds tokenization methods directly onto [`Lexer`]
//! via `impl` blocks.  Whitespace and comments are silently discarded before
//! each dispatch.
//!
//! # Sub-modules
//!
//! | Sub-module | Role |
//! |---|---|
//! | `parser` | Tokenization methods on [`Lexer`] and [`LexError`] variants |
//!
//! # Example
//!
//! ```rust,no_run
//! # use mutant_lang::lexer::Lexer;
//! let lexer = Lexer::new("let x = 42;".to_string());
//! let tokens = lexer.tokenize_all().unwrap();
//! assert!(!tokens.is_empty());
//! ```

use crate::token::{Token, TokenPosition, TokenType};
use thiserror::Error;

/// Errors produced by the lexer when source text cannot be tokenized.
///
/// Every variant records the `(line, col)` position of the character that
/// triggered the error. The human-readable messages are generated by the
/// [`thiserror`] `#[error(…)]` attributes and are suitable for direct display
/// to the user.
#[derive(Debug, Error)]
pub enum LexError {
    /// A string literal was opened with `'` or `"` but the matching closing
    /// quote was never found before end-of-file.
    ///
    /// The position identifies the end-of-file location where the lexer gave
    /// up, not the opening quote.
    #[error("unterminated string literal at {line}:{col}")]
    UnterminatedString { line: usize, col: usize },

    /// An f-string was opened with `f"` but the closing `"` was never found
    /// before end-of-file.
    ///
    /// The position identifies the end-of-file location where the lexer gave
    /// up, not the `f"` opener.
    #[error("unterminated f-string at {line}:{col}")]
    UnterminatedFString { line: usize, col: usize },

    /// A `}` was encountered inside an f-string without a matching `{`.
    ///
    /// This is distinct from [`UnclosedBrace`](LexError::UnclosedBrace): the
    /// brace depth would go negative here, meaning the closing brace is
    /// spurious.
    #[error("unmatched '}}' in f-string at {line}:{col}")]
    UnmatchedBrace { line: usize, col: usize },

    /// A `{` inside an f-string was never closed with a matching `}`.
    ///
    /// Detected at the closing `"` of the f-string, when `brace_depth > 0`.
    #[error("unclosed '{{' in f-string at {line}:{col}")]
    UnclosedBrace { line: usize, col: usize },

    /// The lexer encountered a character that does not belong to any
    /// recognized token class.
    ///
    /// `ch` is the offending character; `line` and `col` identify where it
    /// appeared in the source.
    #[error("unrecognized character '{ch}' at {line}:{col}")]
    UnrecognizedChar { ch: char, line: usize, col: usize },

    /// The lexer reached the end of the input while trying to parse a token
    /// that requires more characters (e.g. an identifier, number, or string).
    #[error("unexpected end of file at {0:?}")]
    UnexpectedEOF((usize, usize)),
}

pub mod parser;

/// Tokenizes a Mutant Lang source string into a sequence of [`Token`]s.
pub struct Lexer {
    chars: Vec<char>,
    current_pos: usize,
    line_col: (usize, usize),
    pos_history: Vec<(usize, usize)>,
}

impl Lexer {
    /// Creates a new `Lexer` from a source string.
    ///
    /// Takes ownership of `input` and initializes the character stream and the
    /// full parser pipeline.  The lexer is immediately ready to produce tokens;
    /// no separate initialization step is required.
    #[must_use]
    pub fn new(input: impl Into<String>) -> Self {
        let chars = input.into().chars().collect();
        Self {
            chars,
            current_pos: 0,
            line_col: (1, 1),
            pos_history: vec![(1, 1)],
        }
    }

    /// Consume the current character and move the cursor forward by one position.
    ///
    /// Safe to call when already at end-of-file; the cursor stays at EOF.
    /// Windows-style `\r\n` endings increment the line counter only once.
    pub(super) fn advance(&mut self) {
        self.current_pos += 1;

        let (line, col) = self.line_col;

        self.line_col = match self.current_char() {
            Some('\n') => (line + 1, 0),
            Some('\r') if self.peek_char() == Some('\n') => (line + 1, 0),
            Some(_) => (line, col + 1),
            None => (line, col),
        };

        self.pos_history.push(self.line_col);
    }

    /// Move the cursor backward by up to `steps` positions, restoring
    /// character and `(line, col)` state. Clamps silently if `steps` exceeds
    /// `current_pos`.
    pub(crate) fn backtrack(&mut self, steps: usize) {
        let steps = steps.min(self.current_pos);
        if steps == 0 {
            return;
        }
        self.current_pos -= steps;
        self.line_col = self.pos_history[self.current_pos];
        self.pos_history.truncate(self.current_pos + 1);
    }

    fn skip_non_tokens(&mut self) {
        loop {
            while let Some(curr_char) = self.current_char()
                && curr_char.is_whitespace()
            {
                self.advance();
            }

            if let Some(curr_char) = self.current_char()
                && curr_char == '#'
            {
                while let Some(curr_char) = self.current_char()
                    && curr_char != '\n'
                {
                    self.advance();
                }
                continue;
            }

            if matches!(
                (self.current_char(), self.peek_char()),
                (Some('/'), Some('*'))
            ) {
                self.advance(); // skip '/'
                self.advance(); // skip '*'

                let mut depth = 1;
                while depth > 0 {
                    match (self.current_char(), self.peek_char()) {
                        (None, _) => break, // EOF inside block comment
                        (Some('/'), Some('*')) => {
                            depth += 1;
                            self.advance();
                        }
                        (Some('*'), Some('/')) => {
                            depth -= 1;
                            self.advance();
                        }
                        _ => {}
                    }
                    self.advance();
                }
            } else {
                break;
            }
        }
    }

    pub fn next_token(&mut self) -> Result<Token, LexError> {
        self.skip_non_tokens();

        let Some(trigger_char) = self.current_char() else {
            return Ok(Token::new(
                TokenType::Eof,
                String::new(),
                TokenPosition::new(self.line_col.0, self.line_col.1),
            ));
        };

        // f-string must be checked before identifier since 'f' is also a letter.
        // parse_identifier and parse_number backtrack to the last char of the token,
        // so we advance once after them. The other parsers advance past their token
        // internally, so no extra advance is needed.
        let token = if trigger_char == 'f' && matches!(self.peek_char(), Some('\'' | '"')) {
            self.parse_f_string()?
        } else if Self::is_letter(trigger_char) {
            let t = self.parse_identifier();
            self.advance();
            t
        } else if Self::is_digit(trigger_char)
            || (trigger_char == '.' && self.peek_char().is_some_and(Self::is_digit))
        {
            let t = self.parse_number();
            self.advance();
            t
        } else if matches!(trigger_char, '\'' | '"') {
            self.parse_string()?
        } else {
            self.parse_operator()?
        };

        Ok(token)
    }

    /// Consumes the lexer and tokenizes the entire input into a [`Vec<Token>`].
    ///
    /// Repeatedly calls [`next_token`](Self::next_token) until an
    /// [`crate::token::TokenType::Eof`] token is produced.  The `Eof` token is
    /// **not** included in the returned vector.
    ///
    /// Because this method takes `self` by value, the `Lexer` cannot be used
    /// after this call — the input string and stream are dropped when the
    /// method returns.
    ///
    /// # Errors
    ///
    /// Propagates any [`LexError`] returned by [`next_token`](Self::next_token).
    /// On error the partial token list is discarded.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// # use mutant_lang::lexer::Lexer;
    /// let tokens = Lexer::new("let x = 1 + 2;".to_string())
    ///     .tokenize_all()
    ///     .unwrap();
    /// assert!(!tokens.is_empty());
    /// ```
    pub fn tokenize_all(mut self) -> Result<Vec<Token>, LexError> {
        let mut tokens = Vec::new();
        loop {
            let token = self.next_token()?;
            if token.kind == TokenType::Eof {
                break;
            }
            tokens.push(token);
        }

        Ok(tokens)
    }

    const fn current_position(&self) -> usize {
        self.current_pos
    }

    fn current_char(&self) -> Option<char> {
        self.chars.get(self.current_pos).copied()
    }

    fn peek_char(&self) -> Option<char> {
        self.chars.get(self.current_pos + 1).copied()
    }

    /// Source text in the half-open range `[start, current_pos)`.
    pub(super) fn get_substring(&self, start: usize) -> String {
        self.chars[start..self.current_pos].iter().collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::token::TokenType;

    /// Helper: tokenize a &str, panic on lex error (for tests that don't expect errors).
    fn tokenize(input: &str) -> Vec<crate::token::Token> {
        Lexer::new(input.to_string()).tokenize_all().unwrap()
    }

    /// Helper: extract just the kinds for compact assertions.
    fn kinds(tokens: &[crate::token::Token]) -> Vec<TokenType> {
        tokens.iter().map(|t| t.kind).collect()
    }

    #[test]
    fn test_tokenize_all_empty_input_returns_empty_vec() {
        assert!(tokenize("").is_empty());
    }

    #[test]
    fn test_tokenize_all_whitespace_only_returns_empty_vec() {
        assert!(tokenize("   \t\n  ").is_empty());
    }

    #[test]
    fn test_tokenize_all_excludes_eof_sentinel() {
        let tokens = tokenize("x ");
        assert!(
            tokens.iter().all(|t| t.kind != TokenType::Eof),
            "tokenize_all must not include the Eof token in its output"
        );
    }

    #[test]
    fn test_tokenize_all_single_identifier() {
        let tokens = tokenize("hello");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Identifier);
        assert_eq!(tokens[0].literal, "hello");
    }

    #[test]
    fn test_tokenize_all_identifier_with_digits_and_underscores() {
        let tokens = tokenize("_var_123");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Identifier);
        assert_eq!(tokens[0].literal, "_var_123");
    }

    #[test]
    fn test_tokenize_all_single_integer() {
        let tokens = tokenize("42");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Int);
        assert_eq!(tokens[0].literal, "42");
    }

    #[test]
    fn test_tokenize_all_zero_integer() {
        let tokens = tokenize("0");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Int);
        assert_eq!(tokens[0].literal, "0");
    }

    #[test]
    fn test_tokenize_all_single_float() {
        let tokens = tokenize("3.14");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Float);
        assert_eq!(tokens[0].literal, "3.14");
    }

    #[test]
    fn test_tokenize_all_leading_dot_float() {
        let tokens = tokenize(".5");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Float);
        assert_eq!(tokens[0].literal, ".5");
    }

    #[test]
    fn test_tokenize_all_all_keywords_mapped_correctly() {
        let cases = [
            ("fn", TokenType::Function),
            ("let", TokenType::Let),
            ("const", TokenType::Const),
            ("if", TokenType::If),
            ("else", TokenType::Else),
            ("elif", TokenType::Elif),
            ("return", TokenType::Return),
            ("while", TokenType::While),
            ("for", TokenType::For),
            ("break", TokenType::Break),
            ("continue", TokenType::Continue),
            ("true", TokenType::True),
            ("false", TokenType::False),
            ("null", TokenType::Null),
            ("class", TokenType::Class),
            ("extends", TokenType::Extends),
            ("super", TokenType::Super),
            ("this", TokenType::This),
            ("new", TokenType::New),
        ];
        for (kw, expected) in cases {
            let tokens = tokenize(kw);
            assert_eq!(
                tokens.len(),
                1,
                "keyword '{kw}' should produce exactly one token"
            );
            assert_eq!(
                tokens[0].kind, expected,
                "keyword '{kw}' mapped to wrong TokenType"
            );
            assert_eq!(
                tokens[0].literal, kw,
                "keyword literal must echo source text"
            );
        }
    }

    #[test]
    fn test_tokenize_all_keyword_prefix_is_identifier() {
        // Tokens that *start with* a keyword but are longer must be Identifiers
        let tokens = tokenize("ifx lett elsex returning");
        assert_eq!(tokens.len(), 4);
        assert!(
            tokens.iter().all(|t| t.kind == TokenType::Identifier),
            "extended keyword-prefix tokens must be Identifiers"
        );
    }

    #[test]
    fn test_tokenize_all_arithmetic_operators() {
        let tokens = tokenize("+ - * / % ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::Plus,
                TokenType::Minus,
                TokenType::Asterisk,
                TokenType::Slash,
                TokenType::Modulus,
            ]
        );
    }

    #[test]
    fn test_tokenize_all_comparison_operators() {
        let tokens = tokenize("< > <= >= == != ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::LessThan,
                TokenType::GreaterThan,
                TokenType::LessThanOrEqual,
                TokenType::GreaterThanOrEqual,
                TokenType::Eq,
                TokenType::NotEq,
            ]
        );
    }

    #[test]
    fn test_tokenize_all_logical_operators() {
        let tokens = tokenize("! && || ");
        assert_eq!(
            kinds(&tokens),
            vec![TokenType::Bang, TokenType::And, TokenType::Or]
        );
    }

    #[test]
    fn test_tokenize_all_compound_assignment_operators() {
        let tokens = tokenize("+= -= *= /= %= ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::PlusAssign,
                TokenType::MinusAssign,
                TokenType::AsteriskAssign,
                TokenType::SlashAssign,
                TokenType::ModulusAssign,
            ]
        );
    }

    #[test]
    fn test_tokenize_all_bitwise_operators() {
        let tokens = tokenize("& | ^ ~ << >> ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::BitwiseAnd,
                TokenType::BitwiseOr,
                TokenType::BitwiseXor,
                TokenType::BitwiseNot,
                TokenType::BitwiseLeftShift,
                TokenType::BitwiseRightShift,
            ]
        );
    }

    #[test]
    fn test_tokenize_all_int_division_operator() {
        let tokens = tokenize("// ");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::IntDivision);
        assert_eq!(tokens[0].literal, "//");
    }

    #[test]
    fn test_tokenize_all_single_equals_vs_double_equals() {
        // '=' + space → Assign (not confused with '==' because peek is ' ')
        let tokens = tokenize("= == ");
        assert_eq!(tokens[0].kind, TokenType::Assign);
        assert_eq!(tokens[0].literal, "=");
        assert_eq!(tokens[1].kind, TokenType::Eq);
        assert_eq!(tokens[1].literal, "==");
    }

    #[test]
    fn test_tokenize_all_bang_vs_not_eq() {
        let tokens = tokenize("! != ");
        assert_eq!(tokens[0].kind, TokenType::Bang);
        assert_eq!(tokens[1].kind, TokenType::NotEq);
    }

    #[test]
    fn test_tokenize_all_all_delimiters() {
        // trailing space keeps peek_char safe on the final '.'
        let tokens = tokenize("( ) [ ] { } , ; : . ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::LParen,
                TokenType::RParen,
                TokenType::LBracket,
                TokenType::RBracket,
                TokenType::LBrace,
                TokenType::RBrace,
                TokenType::Comma,
                TokenType::Semicolon,
                TokenType::Colon,
                TokenType::Dot,
            ]
        );
    }

    #[test]
    fn test_tokenize_all_double_quoted_string() {
        let tokens = tokenize("\"hello world\"");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::String);
        assert_eq!(tokens[0].literal, "hello world");
    }

    #[test]
    fn test_tokenize_all_single_quoted_string() {
        let tokens = tokenize("'hello world'");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::String);
        assert_eq!(tokens[0].literal, "hello world");
    }

    #[test]
    fn test_tokenize_all_empty_string() {
        let tokens = tokenize("\"\"");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::String);
        assert_eq!(tokens[0].literal, "");
    }

    #[test]
    fn test_tokenize_all_string_escape_sequences_expanded() {
        // Escape sequences must be decoded by the lexer
        let tokens = tokenize("\"a\\nb\\tc\\rd\\\\e\\\"f\"");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].literal, "a\nb\tc\rd\\e\"f");
    }

    #[test]
    fn test_tokenize_all_fstring_basic_interpolation() {
        let tokens = tokenize("f\"hello {name}\"");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::FString);
        assert_eq!(tokens[0].literal, "hello {name}");
    }

    #[test]
    fn test_tokenize_all_fstring_takes_priority_over_bare_f_identifier() {
        // 'f' immediately followed by '"' must produce FString, not Identifier + String
        let tokens = tokenize("f\"test\"");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::FString);
    }

    #[test]
    fn test_tokenize_all_f_without_quote_is_identifier() {
        // 'f' followed by a non-quote character is a plain identifier
        let tokens = tokenize("foo");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Identifier);
        assert_eq!(tokens[0].literal, "foo");
    }

    #[test]
    fn test_next_token_empty_input_returns_eof() {
        let mut lexer = Lexer::new(String::new());
        let tok = lexer
            .next_token()
            .expect("empty input should produce an EOF token");
        assert_eq!(tok.kind, TokenType::Eof);
    }

    #[test]
    fn test_next_token_repeated_calls_past_eof_return_eof() {
        // Eof is idempotent — callers can overshoot without error
        let mut lexer = Lexer::new("x".to_string());
        let _id = lexer.next_token().unwrap();
        let eof1 = lexer.next_token().unwrap();
        let eof2 = lexer.next_token().unwrap();
        assert_eq!(eof1.kind, TokenType::Eof);
        assert_eq!(eof2.kind, TokenType::Eof);
    }

    #[test]
    fn test_next_token_produces_tokens_in_order() {
        let mut lexer = Lexer::new("let x ".to_string());
        let t1 = lexer.next_token().unwrap();
        let t2 = lexer.next_token().unwrap();
        let t3 = lexer.next_token().unwrap();
        assert_eq!(t1.kind, TokenType::Let);
        assert_eq!(t2.kind, TokenType::Identifier);
        assert_eq!(t2.literal, "x");
        assert_eq!(t3.kind, TokenType::Eof);
    }

    #[test]
    fn test_next_token_unknown_char_yields_illegal_not_error() {
        let mut lexer = Lexer::new("@ ".to_string());
        let tok = lexer.next_token().unwrap();
        assert_eq!(tok.kind, TokenType::Illegal);
        assert_eq!(tok.literal, "@");
    }

    #[test]
    fn test_next_token_illegal_char_does_not_stop_lexing() {
        let mut lexer = Lexer::new("@ x".to_string());
        let illegal = lexer.next_token().unwrap();
        let id = lexer.next_token().unwrap();
        assert_eq!(illegal.kind, TokenType::Illegal);
        assert_eq!(id.kind, TokenType::Identifier);
        assert_eq!(id.literal, "x");
    }

    #[test]
    fn test_tokenize_all_multiple_illegal_chars() {
        let tokens = tokenize("@ $ `");
        assert_eq!(tokens.len(), 3);
        assert!(tokens.iter().all(|t| t.kind == TokenType::Illegal));
    }

    #[test]
    fn test_next_token_unterminated_string_returns_err() {
        let mut lexer = Lexer::new("\"unterminated".to_string());
        assert!(lexer.next_token().is_err());
    }

    #[test]
    fn test_tokenize_all_unterminated_string_returns_err() {
        let result = Lexer::new("let x = \"unterminated".to_string()).tokenize_all();
        assert!(result.is_err());
    }

    #[test]
    fn test_tokenize_all_unterminated_fstring_returns_err() {
        let result = Lexer::new("f\"unclosed expression".to_string()).tokenize_all();
        assert!(result.is_err());
    }

    #[test]
    fn test_next_token_block_comment_is_skipped() {
        let mut lexer = Lexer::new("/* comment */ x".to_string());
        let tok = lexer.next_token().unwrap();
        assert_eq!(tok.kind, TokenType::Identifier);
        assert_eq!(tok.literal, "x");
    }

    #[test]
    fn test_next_token_nested_block_comment_skipped_via_depth_tracking() {
        // depth increments for inner '/*', decrements for each '*/' in turn
        let mut lexer = Lexer::new("/* outer /* inner */ still outer */ x".to_string());
        let tok = lexer.next_token().unwrap();
        assert_eq!(tok.kind, TokenType::Identifier);
        assert_eq!(tok.literal, "x");
    }

    #[test]
    fn test_tokenize_all_block_comment_between_tokens() {
        let tokens = tokenize("x /* skip this */ y");
        assert_eq!(tokens.len(), 2);
        assert_eq!(tokens[0].literal, "x");
        assert_eq!(tokens[1].literal, "y");
    }

    #[test]
    fn test_tokenize_all_block_comment_only_returns_empty() {
        // A file that is entirely a comment produces no tokens
        let tokens = tokenize("/* entirely a comment */");
        assert!(tokens.is_empty());
    }

    #[test]
    fn test_tokenize_all_multiple_sequential_block_comments() {
        let tokens = tokenize("/* a */ x /* b */ y /* c */");
        assert_eq!(tokens.len(), 2);
        assert_eq!(tokens[0].literal, "x");
        assert_eq!(tokens[1].literal, "y");
    }

    #[test]
    fn test_tokenize_all_first_token_on_first_line() {
        let tokens = tokenize("x");
        assert!(
            tokens[0].position.to_string().starts_with("line 1"),
            "first token must report line 1, got {}",
            tokens[0].position
        );
    }

    #[test]
    fn test_tokenize_all_token_after_newline_on_second_line() {
        let tokens = tokenize("x\ny");
        assert!(
            tokens[1].position.to_string().starts_with("line 2"),
            "token after newline must report line 2, got {}",
            tokens[1].position
        );
    }

    #[test]
    fn test_tokenize_all_multiline_produces_correct_token_count() {
        // "let x\nlet y" → Let, Identifier, Let, Identifier — 4 tokens, no Eof
        let tokens = tokenize("let x\nlet y");
        assert_eq!(tokens.len(), 4);
        assert_eq!(tokens[0].kind, TokenType::Let);
        assert_eq!(tokens[1].literal, "x");
        assert_eq!(tokens[2].kind, TokenType::Let);
        assert_eq!(tokens[3].literal, "y");
    }

    #[test]
    fn test_tokenize_all_let_binding() {
        // trailing space keeps peek_char safe on ';'
        let tokens = tokenize("let x = 5; ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::Let,
                TokenType::Identifier,
                TokenType::Assign,
                TokenType::Int,
                TokenType::Semicolon,
            ]
        );
        assert_eq!(tokens[1].literal, "x");
        assert_eq!(tokens[3].literal, "5");
    }

    #[test]
    fn test_tokenize_all_function_definition() {
        let tokens = tokenize("fn add(a, b) { a + b } ");
        assert_eq!(tokens[0].kind, TokenType::Function);
        assert_eq!(tokens[1].kind, TokenType::Identifier);
        assert_eq!(tokens[1].literal, "add");
        assert!(tokens.iter().any(|t| t.kind == TokenType::Plus));
        assert!(tokens.iter().any(|t| t.kind == TokenType::LParen));
        assert!(tokens.iter().any(|t| t.kind == TokenType::RParen));
        assert!(tokens.iter().any(|t| t.kind == TokenType::LBrace));
        assert!(tokens.iter().any(|t| t.kind == TokenType::RBrace));
    }

    #[test]
    fn test_tokenize_all_if_elif_else_chain() {
        let tokens = tokenize("if a elif b else c");
        assert_eq!(tokens[0].kind, TokenType::If);
        assert_eq!(tokens[2].kind, TokenType::Elif);
        assert_eq!(tokens[4].kind, TokenType::Else);
    }

    #[test]
    fn test_tokenize_all_class_with_extends() {
        let tokens = tokenize("class Animal extends Base ");
        assert_eq!(
            kinds(&tokens),
            vec![
                TokenType::Class,
                TokenType::Identifier,
                TokenType::Extends,
                TokenType::Identifier,
            ]
        );
        assert_eq!(tokens[1].literal, "Animal");
        assert_eq!(tokens[3].literal, "Base");
    }

    #[test]
    fn test_tokenize_all_balanced_delimiters_in_nested_structure() {
        // Every delimiter must be surrounded by whitespace.  OperatorParser::parse
        // calls stream.advance() internally, and next_token advances again after
        // parse() returns, so a single-char operator consumes TWO characters.
        // Without the surrounding spaces, the char immediately after `{` or `[`
        // would be silently skipped and the token stream would be corrupted.
        let tokens = tokenize("{ [ 1 , 2 ] , { 3 , 4 } } ");
        let open = tokens
            .iter()
            .filter(|t| t.kind == TokenType::LBrace)
            .count()
            + tokens
                .iter()
                .filter(|t| t.kind == TokenType::LBracket)
                .count();
        let close = tokens
            .iter()
            .filter(|t| t.kind == TokenType::RBrace)
            .count()
            + tokens
                .iter()
                .filter(|t| t.kind == TokenType::RBracket)
                .count();
        assert_eq!(
            open, close,
            "all opening delimiters must have a matching closer"
        );
    }

    #[test]
    fn test_tokenize_all_fibonacci_function() {
        // Ends with '\n' so the closing '}' has a following char for peek_char
        let src = "fn fibonacci(n) {\nif (n <= 1) { return n }\nreturn fibonacci(n - 1) + fibonacci(n - 2)\n}\n";
        let tokens = tokenize(src);
        assert!(tokens.iter().any(|t| t.kind == TokenType::Function));
        assert!(tokens.iter().any(|t| t.kind == TokenType::If));
        assert!(tokens.iter().any(|t| t.kind == TokenType::Return));
        assert!(tokens.iter().any(|t| t.kind == TokenType::LessThanOrEqual));
        assert!(
            tokens
                .iter()
                .any(|t| t.kind == TokenType::Identifier && t.literal == "fibonacci"),
            "function name 'fibonacci' must appear as an identifier"
        );
    }

    #[test]
    fn test_tokenize_all_very_long_identifier() {
        let long: String = "a".repeat(1001);
        let tokens = tokenize(&long);
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Identifier);
        assert_eq!(tokens[0].literal.len(), 1001);
    }

    #[test]
    fn test_tokenize_all_very_long_integer_literal() {
        let long: String = "9".repeat(200);
        let tokens = tokenize(&long);
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].kind, TokenType::Int);
        assert_eq!(tokens[0].literal.len(), 200);
    }
}
