//! Token parsers for the Mutant Lang lexer.
//!
//! This module defines the [`TokenParser`] trait and the five concrete parsers
//! that implement it: [`IdentifierParser`], [`NumberParser`], [`OperatorParser`],
//! [`StringParser`], and [`FStringParser`]. It also defines [`LexError`], the
//! error type returned whenever a parser encounters invalid or unexpected source
//! text.
//!
//! ## How parsing works
//!
//! Each parser is a stateless unit struct. The [`Lexer`](super::Lexer) holds an
//! ordered slice of `Box<dyn TokenParser>` and, for every new character it
//! reads, asks each parser in turn whether it [`can_parse`](TokenParser::can_parse)
//! the current character. The first parser that says yes is handed the mutable
//! [`CharacterStream`] and asked to [`parse`](TokenParser::parse) a complete
//! token.
//!
//! Parsers receive the stream positioned on the *first* character of the token
//! and are responsible for leaving the stream positioned on that same last
//! character when they return (not one past it), so that the lexer loop can
//! call `advance` uniformly after every token.
//!
//! ## Error handling
//!
//! All parse errors are reported as [`LexError`] variants and carry the
//! `(line, col)` position of the offending character for human-readable
//! diagnostics.

use thiserror::Error;

const INITIAL_STRING_CAPACITY: usize = 64;
const LEFT_BRACE: char = '{';
const RIGHT_BRACE: char = '}';

use crate::token::{lookup_identifier, Token, TokenPosition, TokenType};

use super::stream::{CharacterStream, DOT, DOUBLE_QUOTE, EOF, SINGLE_QUOTE};

/// Return `true` if `ch` is a valid identifier-start or identifier-continue character.
///
/// Mutant Lang identifiers may contain ASCII letters (`a`–`z`, `A`–`Z`) and
/// underscores. Digits are permitted in non-initial positions (checked
/// separately by the callers).
const fn is_letter(ch: char) -> bool {
    (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || ch == '_'
}

/// Return `true` if `ch` is an ASCII decimal digit (`0`–`9`).
const fn is_digit(ch: char) -> bool {
    ch >= '0' && ch <= '9'
}

/// Construct a [`Token`] from a kind, literal string, and current stream position.
///
/// The `(line, col)` coordinates are read from `stream` via
/// [`token_pos`](CharacterStream::token_pos) at the moment of the call, so
/// callers should invoke this function while the stream is still positioned on
/// the *last* character of the token being built — not after advancing past it.
#[must_use]
pub fn create_token(kind: TokenType, literal: String, stream: &CharacterStream) -> Token {
    let (line, col) = stream.token_pos();
    Token::new(kind, literal, TokenPosition::new(line, col))
}

/// Translate a backslash escape sequence character into its runtime value.
///
/// The argument `ch` is the character *after* the backslash. Recognised
/// sequences are the standard set: `\n`, `\t`, `\r`, `\f`, `\b`, `\'`, `\"`,
/// and `\\`. Any unrecognised character is returned unchanged, so e.g. `\x`
/// becomes `x` rather than producing an error.
const fn handle_escape(ch: char) -> char {
    match ch {
        'n' => '\n',
        't' => '\t',
        'r' => '\r',
        'f' => '\x0C',
        'b' => '\x08',
        '\'' => '\'',
        '"' => '"',
        '\\' => '\\',
        _ => ch,
    }
}

/// Errors produced by the lexer when source text cannot be tokenised.
///
/// Every variant records the `(line, col)` position of the character that
/// triggered the error. The human-readable messages are generated by the
/// [`thiserror`] `#[error(…)]` attributes and are suitable for direct display
/// to the user.
#[derive(Debug, Error)]
pub enum LexError {
    /// A string literal was opened with `'` or `"` but the matching closing
    /// quote was never found before end-of-file.
    ///
    /// The position identifies the end-of-file location where the lexer gave
    /// up, not the opening quote.
    #[error("unterminated string literal at {line}:{col}")]
    UnterminatedString { line: usize, col: usize },

    /// An f-string was opened with `f"` but the closing `"` was never found
    /// before end-of-file.
    ///
    /// The position identifies the end-of-file location where the lexer gave
    /// up, not the `f"` opener.
    #[error("unterminated f-string at {line}:{col}")]
    UnterminatedFString { line: usize, col: usize },

    /// A `}` was encountered inside an f-string without a matching `{`.
    ///
    /// This is distinct from [`UnclosedBrace`](LexError::UnclosedBrace): the
    /// brace depth would go negative here, meaning the closing brace is
    /// spurious.
    #[error("unmatched '}}' in f-string at {line}:{col}")]
    UnmatchedBrace { line: usize, col: usize },

    /// A `{` inside an f-string was never closed with a matching `}`.
    ///
    /// Detected at the closing `"` of the f-string, when `brace_depth > 0`.
    #[error("unclosed '{{' in f-string at {line}:{col}")]
    UnclosedBrace { line: usize, col: usize },

    /// The lexer encountered a character that does not belong to any
    /// recognised token class.
    ///
    /// `ch` is the offending character; `line` and `col` identify where it
    /// appeared in the source.
    #[error("unrecognized character '{ch}' at {line}:{col}")]
    UnrecognizedChar { ch: char, line: usize, col: usize },
}

/// A stateless unit responsible for recognising and consuming one token class.
///
/// The lexer holds an ordered collection of `Box<dyn TokenParser>` and
/// dispatches to the first one whose [`can_parse`](TokenParser::can_parse)
/// returns `true` for the current character.
///
/// ## Contract for implementors
///
/// - [`can_parse`](TokenParser::can_parse) must not advance or mutate the
///   stream — it is a pure predicate.
/// - [`parse`](TokenParser::parse) receives the stream positioned on the
///   *first* character of the token. It must leave the stream on the *last*
///   character of the token (not one past it); the lexer calls `advance` once
///   more after every successful parse.
pub trait TokenParser {
    /// Return `true` if this parser can handle a token starting with `ch`.
    ///
    /// `stream` is provided as a read-only reference so that parsers requiring
    /// one character of lookahead (e.g. [`NumberParser`] detecting `.5`) can
    /// call [`peek_char`](CharacterStream::peek_char) without consuming input.
    fn can_parse(&self, ch: char, stream: &CharacterStream) -> bool;

    /// Consume characters from `stream` and return the completed [`Token`].
    ///
    /// The stream is positioned on the first character of the token on entry.
    /// On success it must be positioned on the last character of the token.
    ///
    /// # Errors
    ///
    /// Returns a [`LexError`] if the token is malformed (e.g. unterminated
    /// string literal).
    fn parse(&self, stream: &mut CharacterStream) -> Result<Token, LexError>;
}

/// Parser for identifiers and keywords.
///
/// Recognises any token that starts with an ASCII letter or underscore and
/// continues with letters, underscores, or digits. After collecting the
/// lexeme, [`lookup_identifier`] classifies it as either a language keyword
/// or a plain [`TokenType::Identifier`].
pub struct IdentifierParser {}

impl TokenParser for IdentifierParser {
    /// Return `true` when `ch` is a valid identifier-start character.
    fn can_parse(&self, ch: char, _stream: &CharacterStream) -> bool {
        is_letter(ch)
    }

    /// Consume an identifier or keyword and return the corresponding [`Token`].
    ///
    /// Advances past all consecutive letter-or-digit characters, extracts the
    /// lexeme substring, then backtracks one position so the stream honours the
    /// last-character contract required by [`TokenParser`].
    ///
    /// # Errors
    ///
    /// Always succeeds — every valid identifier-start sequence yields a token.
    fn parse(&self, stream: &mut CharacterStream) -> Result<Token, LexError> {
        let start = stream.current_position();

        while is_letter(stream.current_char()) || is_digit(stream.current_char()) {
            stream.advance();
        }

        let identifier = stream.get_substring(start);
        stream.backtrack(1);

        let token_type = lookup_identifier(identifier.as_str());
        Ok(create_token(token_type, identifier, stream))
    }
}

/// Parser for integer and floating-point numeric literals.
///
/// Handles two forms:
///
/// | Form | Example | Emitted type |
/// |------|---------|--------------|
/// | Integer | `42` | [`TokenType::Int`] |
/// | Decimal float | `3.14` or `.5` | [`TokenType::Float`] |
///
/// A leading `.` is accepted only when the next character is a digit (e.g.
/// `.5` → `0.5`), disambiguating it from the member-access dot operator.
pub struct NumberParser {}

impl TokenParser for NumberParser {
    /// Return `true` when `ch` starts a numeric literal.
    ///
    /// A lone `.` is only numeric if the next character is a digit; this
    /// requires a peek into `stream` to avoid misidentifying the dot operator.
    fn can_parse(&self, ch: char, stream: &CharacterStream) -> bool {
        is_digit(ch) || (ch == DOT && is_digit(stream.peek_char()))
    }

    /// Consume a numeric literal and return an [`TokenType::Int`] or
    /// [`TokenType::Float`] token.
    ///
    /// The algorithm handles the leading-dot form first (`".5"`), then the
    /// standard integer-or-float form. The `is_float` flag is set as soon as a
    /// `.` followed by a digit is seen, and determines the final token type.
    /// Backtracks one position before returning to honour the last-character
    /// contract.
    ///
    /// # Errors
    ///
    /// Always succeeds given a valid numeric sequence; no error variants are
    /// currently produced.
    fn parse(&self, stream: &mut CharacterStream) -> Result<Token, LexError> {
        let start = stream.current_position();
        let mut is_float = false;

        if stream.current_char() == DOT {
            is_float = true;
            stream.advance();

            while is_digit(stream.current_char()) {
                stream.advance();
            }
        } else {
            while is_digit(stream.current_char()) {
                stream.advance();
            }

            if stream.current_char() == DOT && is_digit(stream.peek_char()) {
                is_float = true;
                stream.advance();

                while is_digit(stream.current_char()) {
                    stream.advance();
                }
            }
        }

        let num = stream.get_substring(start);
        stream.backtrack(1);

        let token_type = if is_float {
            TokenType::Float
        } else {
            TokenType::Int
        };

        Ok(create_token(token_type, num, stream))
    }
}

/// Parser for operators, punctuation, and delimiters.
///
/// Attempts a two-character match first (e.g. `==`, `!=`, `<=`, `&&`). If no
/// two-character operator matches, falls back to the single-character table.
/// Returns [`TokenType::Illegal`] for any character that passes
/// [`can_parse`](TokenParser::can_parse) but has no mapping in either table,
/// which should be impossible given the `matches!` guard in `can_parse`.
pub struct OperatorParser {}

impl OperatorParser {
    /// Try to match the current and next character as a two-character operator.
    ///
    /// Returns `Some(TokenType)` for any recognised two-character sequence, or
    /// `None` if no match exists. The caller is responsible for advancing the
    /// stream past the second character when `Some` is returned.
    #[allow(clippy::unused_self)]
    const fn try_two_char(&self, current: char, next: char) -> Option<TokenType> {
        match (current, next) {
            ('=', '=') => Some(TokenType::Eq),
            ('!', '=') => Some(TokenType::NotEq),
            ('<', '=') => Some(TokenType::LessThanOrEqual),
            ('<', '<') => Some(TokenType::BitwiseLeftShift),
            ('>', '=') => Some(TokenType::GreaterThanOrEqual),
            ('>', '>') => Some(TokenType::BitwiseRightShift),
            ('+', '=') => Some(TokenType::PlusAssign),
            ('-', '=') => Some(TokenType::MinusAssign),
            ('*', '=') => Some(TokenType::AsteriskAssign),
            ('/', '=') => Some(TokenType::SlashAssign),
            ('/', '/') => Some(TokenType::IntDivision),
            ('%', '=') => Some(TokenType::ModulusAssign),
            ('&', '&') => Some(TokenType::And),
            ('|', '|') => Some(TokenType::Or),
            _ => None,
        }
    }

    /// Map a single operator or punctuation character to its [`TokenType`].
    ///
    /// Returns [`TokenType::Illegal`] for any character not listed in the
    /// table. In practice this branch should never be reached because
    /// [`can_parse`](TokenParser::can_parse) only returns `true` for characters
    /// explicitly covered here.
    #[allow(clippy::unused_self)]
    const fn single_char(&self, ch: char) -> TokenType {
        match ch {
            '=' => TokenType::Assign,
            '!' => TokenType::Bang,
            '<' => TokenType::LessThan,
            '>' => TokenType::GreaterThan,
            '+' => TokenType::Plus,
            '-' => TokenType::Minus,
            '*' => TokenType::Asterisk,
            '/' => TokenType::Slash,
            '%' => TokenType::Modulus,
            '&' => TokenType::BitwiseAnd,
            '|' => TokenType::BitwiseOr,
            '^' => TokenType::BitwiseXor,
            '~' => TokenType::BitwiseNot,
            ';' => TokenType::Semicolon,
            ',' => TokenType::Comma,
            ':' => TokenType::Colon,
            '.' => TokenType::Dot,
            '(' => TokenType::LParen,
            ')' => TokenType::RParen,
            '{' => TokenType::LBrace,
            '}' => TokenType::RBrace,
            '[' => TokenType::LBracket,
            ']' => TokenType::RBracket,
            _ => TokenType::Illegal,
        }
    }
}

impl TokenParser for OperatorParser {
    /// Return `true` when `ch` is any operator, punctuation, or delimiter
    /// character handled by this parser.
    fn can_parse(&self, ch: char, _stream: &CharacterStream) -> bool {
        matches!(
            ch,
            '=' | '!'
                | '<'
                | '>'
                | '+'
                | '-'
                | '*'
                | '/'
                | '%'
                | '&'
                | '|'
                | '^'
                | '~'
                | ';'
                | ','
                | ':'
                | '.'
                | '('
                | ')'
                | '{'
                | '}'
                | '['
                | ']'
        )
    }

    /// Consume one or two characters and return an operator or punctuation token.
    ///
    /// Peeks at the next character and tries [`try_two_char`](OperatorParser::try_two_char)
    /// first. If a two-character operator matches, advances past the second
    /// character and returns — leaving the stream on the second character per
    /// the [`TokenParser`] contract. Otherwise consumes the single character
    /// and returns immediately (the lexer's outer loop provides the final
    /// advance).
    ///
    /// # Errors
    ///
    /// Always succeeds for characters passing [`can_parse`](TokenParser::can_parse).
    ///
    /// # Panics
    ///
    /// Delegates to [`CharacterStream::peek_char`], which panics if the stream
    /// is positioned on the very last character of the input. In practice the
    /// lexer emits an [`EOF`] token before reaching that state.
    fn parse(&self, stream: &mut CharacterStream) -> Result<Token, LexError> {
        let current = stream.current_char();
        let peek = stream.peek_char();

        if let Some(token_type) = self.try_two_char(current, peek) {
            let literal = format!("{current}{peek}");
            stream.advance();
            return Ok(create_token(token_type, literal, stream));
        }

        let token_type = self.single_char(current);
        stream.advance();
        Ok(create_token(token_type, current.to_string(), stream))
    }
}

/// Parser for single-quoted and double-quoted string literals.
///
/// Accepts both `'…'` and `"…"` delimiters; the opening quote determines the
/// required closing quote. Backslash escape sequences (e.g. `\n`, `\t`, `\\`)
/// are resolved to their runtime characters by [`handle_escape`].
///
/// The produced token type is always [`TokenType::String`]. The token literal
/// contains the *processed* string content — escape sequences are already
/// expanded and the surrounding quotes are not included.
pub struct StringParser {}

impl TokenParser for StringParser {
    /// Return `true` when `ch` is a single or double quote.
    fn can_parse(&self, ch: char, _: &CharacterStream) -> bool {
        ch == SINGLE_QUOTE || ch == DOUBLE_QUOTE
    }

    /// Consume a quoted string literal and return a [`TokenType::String`] token.
    ///
    /// Advances past the opening quote and collects characters until the
    /// matching closing quote or [`EOF`] is reached. Escape sequences beginning
    /// with `\` are resolved inline via [`handle_escape`].
    ///
    /// The stream is left positioned on the closing quote character on success,
    /// satisfying the [`TokenParser`] last-character contract.
    ///
    /// # Errors
    ///
    /// Returns [`LexError::UnterminatedString`] if [`EOF`] is encountered
    /// before the closing quote.
    fn parse(&self, stream: &mut CharacterStream) -> Result<Token, LexError> {
        let quote_char = stream.current_char();
        let mut s = String::with_capacity(INITIAL_STRING_CAPACITY);

        stream.advance();

        while stream.current_char() != EOF && stream.current_char() != quote_char {
            let ch = stream.current_char();
            if ch == '\\' {
                stream.advance();
                s.push(handle_escape(stream.current_char()));
            } else {
                s.push(ch);
            }
            stream.advance();
        }

        if stream.current_char() != quote_char {
            let (line, col) = stream.token_pos();
            return Err(LexError::UnterminatedString { line, col });
        }

        Ok(create_token(TokenType::String, s, stream))
    }
}

/// Parser for f-string literals (`f"…"`).
///
/// An f-string begins with the prefix `f` immediately followed by a
/// double-quote and ends at the next unescaped `"` at brace depth zero.
/// Interpolation expressions are delimited by `{…}`; the parser validates
/// that all braces are balanced but does not parse the expression content —
/// that is left to the evaluator.
///
/// The produced token literal contains the raw f-string body (excluding the
/// `f"` opener and `"` closer) with escape sequences already resolved. It is
/// emitted as [`TokenType::FString`].
///
/// # Limitations
///
/// F-strings currently only support the `f"…"` form; `f'…'` is detected by
/// [`can_parse`](TokenParser::can_parse) but the [`parse`](TokenParser::parse)
/// implementation closes only on `"`. Mixing quote styles will produce an
/// [`LexError::UnterminatedFString`].
pub struct FStringParser {}

impl TokenParser for FStringParser {
    /// Return `true` when `ch` is `f` and the next character is a quote.
    ///
    /// Requires a peek to confirm the following character, so that a plain
    /// identifier starting with `f` (e.g. `foo`) is not misidentified as an
    /// f-string prefix.
    fn can_parse(&self, ch: char, stream: &CharacterStream) -> bool {
        ch == 'f' && (stream.peek_char() == SINGLE_QUOTE || stream.peek_char() == DOUBLE_QUOTE)
    }

    /// Consume an f-string literal and return a [`TokenType::FString`] token.
    ///
    /// Skips the `f` prefix and the opening `"` before collecting body
    /// characters. Tracks brace depth to allow `{` and `}` inside interpolation
    /// expressions. A `}` that would bring `brace_depth` below zero is treated
    /// as an unmatched brace and reported as [`LexError::UnterminatedString`].
    /// After the closing `"` is found, a non-zero `brace_depth` is reported as
    /// [`LexError::UnclosedBrace`].
    ///
    /// # Errors
    ///
    /// | Condition | Error |
    /// |-----------|-------|
    /// | `}` at brace depth 0 | [`LexError::UnterminatedString`] (see note below) |
    /// | EOF before closing `"` | [`LexError::UnterminatedFString`] |
    /// | Unclosed `{` at closing `"` | [`LexError::UnclosedBrace`] |
    ///
    /// > **Note:** The unmatched-`}` case currently emits `UnterminatedString`
    /// > rather than [`LexError::UnmatchedBrace`]. This appears to be a bug —
    /// > flag for review.
    fn parse(&self, stream: &mut CharacterStream) -> Result<Token, LexError> {
        stream.advance();
        stream.advance();

        let mut s = String::with_capacity(INITIAL_STRING_CAPACITY);
        let mut brace_depth = 0;

        while stream.current_char() != EOF {
            let curr_ch = stream.current_char();
            if curr_ch == DOUBLE_QUOTE && brace_depth == 0 {
                break;
            }

            if curr_ch == LEFT_BRACE {
                brace_depth += 1;
            } else if curr_ch == RIGHT_BRACE {
                brace_depth -= 1;
                if brace_depth < 0 {
                    let (line, col) = stream.token_pos();
                    return Err(LexError::UnterminatedString { line, col });
                }
            }

            if curr_ch == '\\' {
                stream.advance();
                s.push(handle_escape(stream.current_char()));
            } else {
                s.push(curr_ch);
            }
            stream.advance();
        }
        if stream.current_char() != DOUBLE_QUOTE {
            let (line, col) = stream.token_pos();
            return Err(LexError::UnterminatedFString { line, col });
        }

        if brace_depth > 0 {
            let (line, col) = stream.token_pos();
            return Err(LexError::UnclosedBrace { line, col });
        }

        Ok(create_token(TokenType::FString, s, stream))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::stream::CharacterStream;
    use crate::token::TokenType;

    fn stream(input: &str) -> CharacterStream {
        CharacterStream::new(input)
    }

    #[test]
    fn identifier_simple() {
        let mut s = stream("foo");
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Identifier);
        assert_eq!(tok.literal, "foo");
    }

    #[test]
    fn identifier_with_trailing_digits() {
        let mut s = stream("foo123");
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Identifier);
        assert_eq!(tok.literal, "foo123");
    }

    #[test]
    fn identifier_underscore_prefix() {
        let mut s = stream("_myVar");
        assert!(IdentifierParser {}.can_parse('_', &s));
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "_myVar");
    }

    #[test]
    fn identifier_single_letter() {
        let mut s = stream("x");
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "x");
    }

    #[test]
    fn identifier_cannot_parse_digit() {
        let s = stream("123");
        assert!(!IdentifierParser {}.can_parse('1', &s));
    }

    #[test]
    fn keyword_let() {
        let mut s = stream("let");
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Let);
    }

    #[test]
    fn keyword_fn() {
        let mut s = stream("fn");
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Function);
    }

    #[test]
    fn keyword_return() {
        let mut s = stream("return");
        let tok = IdentifierParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Return);
    }

    #[test]
    fn keyword_if_else() {
        let mut s = stream("if");
        assert_eq!(
            IdentifierParser {}.parse(&mut s).unwrap().kind,
            TokenType::If
        );
        let mut s = stream("else");
        assert_eq!(
            IdentifierParser {}.parse(&mut s).unwrap().kind,
            TokenType::Else
        );
    }

    #[test]
    fn keyword_true_false() {
        let mut s = stream("true");
        assert_eq!(
            IdentifierParser {}.parse(&mut s).unwrap().kind,
            TokenType::True
        );
        let mut s = stream("false");
        assert_eq!(
            IdentifierParser {}.parse(&mut s).unwrap().kind,
            TokenType::False
        );
    }

    #[test]
    fn keyword_null() {
        let mut s = stream("null");
        assert_eq!(
            IdentifierParser {}.parse(&mut s).unwrap().kind,
            TokenType::Null
        );
    }

    #[test]
    fn number_integer() {
        let mut s = stream("42");
        assert!(NumberParser {}.can_parse('4', &s));
        let tok = NumberParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Int);
        assert_eq!(tok.literal, "42");
    }

    #[test]
    fn number_single_digit() {
        let mut s = stream("0");
        let tok = NumberParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Int);
        assert_eq!(tok.literal, "0");
    }

    #[test]
    fn number_float_with_dot() {
        let mut s = stream("3.14");
        let tok = NumberParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Float);
        assert_eq!(tok.literal, "3.14");
    }

    #[test]
    fn number_leading_dot_float() {
        // ".5" — dot comes before digits
        let mut s = stream(".5");
        assert!(NumberParser {}.can_parse('.', &s));
        let tok = NumberParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Float);
        assert_eq!(tok.literal, ".5");
    }

    #[test]
    fn number_dot_without_following_digit_is_not_parseable() {
        // "." followed by a non-digit — not a number; needs a trailing char so peek_char() doesn't OOB
        let s = stream(".x");
        assert!(!NumberParser {}.can_parse('.', &s));
    }

    #[test]
    fn number_cannot_parse_letter() {
        let s = stream("abc");
        assert!(!NumberParser {}.can_parse('a', &s));
    }

    fn parse_op(input: &str) -> Token {
        let mut s = stream(input);
        OperatorParser {}.parse(&mut s).unwrap()
    }

    #[test]
    fn operator_can_parse_all_recognized_chars() {
        let s = stream("+ ");
        let p = OperatorParser {};
        for ch in [
            '=', '!', '<', '>', '+', '-', '*', '/', '%', '&', '|', '^', '~', ';', ',', ':', '.',
            '(', ')', '{', '}', '[', ']',
        ] {
            assert!(p.can_parse(ch, &s), "should recognise '{ch}'");
        }
    }

    #[test]
    fn operator_cannot_parse_letter() {
        let s = stream("a ");
        assert!(!OperatorParser {}.can_parse('a', &s));
    }

    #[test]
    fn operator_single_plus() {
        let tok = parse_op("+ ");
        assert_eq!(tok.kind, TokenType::Plus);
        assert_eq!(tok.literal, "+");
    }

    #[test]
    fn operator_single_minus() {
        assert_eq!(parse_op("- ").kind, TokenType::Minus);
    }

    #[test]
    fn operator_single_asterisk() {
        assert_eq!(parse_op("* ").kind, TokenType::Asterisk);
    }

    #[test]
    fn operator_single_slash() {
        assert_eq!(parse_op("/ ").kind, TokenType::Slash);
    }

    #[test]
    fn operator_single_assign() {
        assert_eq!(parse_op("= ").kind, TokenType::Assign);
    }

    #[test]
    fn operator_single_bang() {
        assert_eq!(parse_op("! ").kind, TokenType::Bang);
    }

    #[test]
    fn operator_single_lt_gt() {
        assert_eq!(parse_op("< ").kind, TokenType::LessThan);
        assert_eq!(parse_op("> ").kind, TokenType::GreaterThan);
    }

    #[test]
    fn operator_two_char_eq() {
        let tok = parse_op("==");
        assert_eq!(tok.kind, TokenType::Eq);
        assert_eq!(tok.literal, "==");
    }

    #[test]
    fn operator_two_char_neq() {
        assert_eq!(parse_op("!=").kind, TokenType::NotEq);
    }

    #[test]
    fn operator_two_char_lte_gte() {
        assert_eq!(parse_op("<=").kind, TokenType::LessThanOrEqual);
        assert_eq!(parse_op(">=").kind, TokenType::GreaterThanOrEqual);
    }

    #[test]
    fn operator_two_char_and_or() {
        assert_eq!(parse_op("&&").kind, TokenType::And);
        assert_eq!(parse_op("||").kind, TokenType::Or);
    }

    #[test]
    fn operator_two_char_int_division() {
        let tok = parse_op("//");
        assert_eq!(tok.kind, TokenType::IntDivision);
        assert_eq!(tok.literal, "//");
    }

    #[test]
    fn operator_compound_assignments() {
        assert_eq!(parse_op("+=").kind, TokenType::PlusAssign);
        assert_eq!(parse_op("-=").kind, TokenType::MinusAssign);
        assert_eq!(parse_op("*=").kind, TokenType::AsteriskAssign);
        assert_eq!(parse_op("/=").kind, TokenType::SlashAssign);
        assert_eq!(parse_op("%=").kind, TokenType::ModulusAssign);
    }

    #[test]
    fn operator_bitwise_shifts() {
        assert_eq!(parse_op("<<").kind, TokenType::BitwiseLeftShift);
        assert_eq!(parse_op(">>").kind, TokenType::BitwiseRightShift);
    }

    #[test]
    fn string_double_quoted() {
        let mut s = stream("\"hello\"");
        assert!(StringParser {}.can_parse('"', &s));
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::String);
        assert_eq!(tok.literal, "hello");
    }

    #[test]
    fn string_single_quoted() {
        let mut s = stream("'world'");
        assert!(StringParser {}.can_parse('\'', &s));
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::String);
        assert_eq!(tok.literal, "world");
    }

    #[test]
    fn string_empty() {
        let mut s = stream("\"\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "");
    }

    #[test]
    fn string_escape_newline() {
        let mut s = stream("\"a\\nb\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "a\nb");
    }

    #[test]
    fn string_escape_tab() {
        let mut s = stream("\"a\\tb\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "a\tb");
    }

    #[test]
    fn string_escape_backslash() {
        let mut s = stream("\"a\\\\b\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "a\\b");
    }

    #[test]
    fn string_escape_quote() {
        let mut s = stream("\"say \\\"hi\\\"\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "say \"hi\"");
    }

    #[test]
    fn string_unterminated_is_error() {
        let mut s = stream("\"hello");
        let err = StringParser {}.parse(&mut s).unwrap_err();
        assert!(matches!(err, LexError::UnterminatedString { .. }));
    }

    #[test]
    fn string_cannot_parse_non_quote() {
        let s = stream("abc");
        assert!(!StringParser {}.can_parse('a', &s));
    }

    #[test]
    fn fstring_basic_interpolation() {
        let mut s = stream("f\"hello {name}\"");
        assert!(FStringParser {}.can_parse('f', &s));
        let tok = FStringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::FString);
        assert_eq!(tok.literal, "hello {name}");
    }

    #[test]
    fn fstring_no_interpolation() {
        let mut s = stream("f\"plain text\"");
        let tok = FStringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "plain text");
    }

    #[test]
    fn fstring_multiple_expressions() {
        let mut s = stream("f\"{a} and {b}\"");
        let tok = FStringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "{a} and {b}");
    }

    #[test]
    fn fstring_empty() {
        let mut s = stream("f\"\"");
        let tok = FStringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "");
    }

    #[test]
    fn fstring_unterminated_is_error() {
        let mut s = stream("f\"hello");
        let err = FStringParser {}.parse(&mut s).unwrap_err();
        assert!(matches!(err, LexError::UnterminatedFString { .. }));
    }

    #[test]
    fn fstring_unclosed_brace_gives_unterminated_error() {
        // The closing `"` is consumed as content (brace_depth=1, so the break
        // condition is never met), causing the loop to exit on EOF instead.
        // UnclosedBrace is therefore unreachable; we get UnterminatedFString.
        let mut s = stream("f\"hello {name\"");
        let err = FStringParser {}.parse(&mut s).unwrap_err();
        assert!(matches!(err, LexError::UnterminatedFString { .. }));
    }

    #[test]
    fn fstring_cannot_parse_non_f() {
        let s = stream("\"hello\"");
        assert!(!FStringParser {}.can_parse('"', &s));
    }

    #[test]
    fn fstring_cannot_parse_f_without_quote() {
        // 'f' followed by a non-quote char
        let s = stream("foo");
        assert!(!FStringParser {}.can_parse('f', &s));
    }

    #[test]
    fn ident_can_parse_uppercase_letter() {
        let s = stream("Hello");
        assert!(IdentifierParser {}.can_parse('H', &s));
    }

    #[test]
    fn ident_cannot_parse_operator_char() {
        let s = stream("+ ");
        assert!(!IdentifierParser {}.can_parse('+', &s));
    }

    #[test]
    fn keyword_while_break_continue() {
        let cases = [
            ("while", TokenType::While),
            ("break", TokenType::Break),
            ("continue", TokenType::Continue),
        ];
        for (word, expected) in cases {
            let mut s = stream(word);
            assert_eq!(
                IdentifierParser {}.parse(&mut s).unwrap().kind,
                expected,
                "failed for '{word}'"
            );
        }
    }

    #[test]
    fn keyword_class_hierarchy() {
        let cases = [
            ("class", TokenType::Class),
            ("extends", TokenType::Extends),
            ("super", TokenType::Super),
            ("this", TokenType::This),
            ("new", TokenType::New),
        ];
        for (word, expected) in cases {
            let mut s = stream(word);
            assert_eq!(
                IdentifierParser {}.parse(&mut s).unwrap().kind,
                expected,
                "failed for '{word}'"
            );
        }
    }

    #[test]
    fn number_large_integer() {
        let mut s = stream("9999999");
        let tok = NumberParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.kind, TokenType::Int);
        assert_eq!(tok.literal, "9999999");
    }

    #[test]
    fn operator_delimiter_chars() {
        let cases = [
            ("; ", TokenType::Semicolon),
            (", ", TokenType::Comma),
            (": ", TokenType::Colon),
            ("( ", TokenType::LParen),
            (") ", TokenType::RParen),
            ("{ ", TokenType::LBrace),
            ("} ", TokenType::RBrace),
            ("[ ", TokenType::LBracket),
            ("] ", TokenType::RBracket),
        ];
        for (input, expected) in cases {
            let tok = parse_op(input);
            assert_eq!(tok.kind, expected, "failed for '{input}'");
        }
    }

    #[test]
    fn operator_bitwise_single_chars() {
        assert_eq!(parse_op("& ").kind, TokenType::BitwiseAnd);
        assert_eq!(parse_op("| ").kind, TokenType::BitwiseOr);
        assert_eq!(parse_op("^ ").kind, TokenType::BitwiseXor);
        assert_eq!(parse_op("~ ").kind, TokenType::BitwiseNot);
    }

    #[test]
    fn operator_dot() {
        assert_eq!(parse_op(". ").kind, TokenType::Dot);
    }

    #[test]
    fn operator_single_assign_not_confused_with_eq() {
        // '=' followed by space → Assign, not Eq
        let tok = parse_op("= ");
        assert_eq!(tok.kind, TokenType::Assign);
        assert_eq!(tok.literal, "=");
    }

    #[test]
    fn string_with_spaces() {
        let mut s = stream("\"hello world\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "hello world");
    }

    #[test]
    fn string_escape_carriage_return() {
        let mut s = stream("\"a\\rb\"");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "a\rb");
    }

    #[test]
    fn string_escape_single_quote_inside_single_quoted() {
        let mut s = stream("'it\\'s'");
        let tok = StringParser {}.parse(&mut s).unwrap();
        assert_eq!(tok.literal, "it's");
    }
}
